@url = http://localhost:8080

### Health check
GET {{url}}/health
Accept: application/json

### Get order by ID
GET {{url}}/orders/befa2802-c2c7-4d2e-a07c-3f0d72ed745c
Accept: application/json

### Create order
POST {{url}}/orders
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 100,
  "buyer_id": "user-1"
}


### Create settlement job
POST {{url}}/jobs/settlement
Content-Type: application/json

{
  "from": "2025-01-10",
  "to": "2025-01-15"
}


### Get job by ID
GET {{url}}/jobs/a345dd08-6718-4d59-bbaa-0b2688f95b08
Accept: application/json

