### Health check
GET http://localhost:8080/health
Accept: application/json



### Create order
POST http://localhost:8080/orders
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 100,
  "buyer_id": "user-1"
}

