@url = http://localhost:8080
@order_id = befa2802-c2c7-4d2e-a07c-3f0d72ed745c

### Health check
GET {{url}}/health
Accept: application/json

### Get order by ID
GET {{url}}/orders/{{order_id}}
Accept: application/json

### Create order
POST {{url}}/orders
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 100,
  "buyer_id": "user-1"
}

